### ISSUE TITLE
tests and docker build show as failed when they passed

### ISSUE THREAD

**Issue by dneilroth** [codeamp/panel#167] opened 2018-05-29 19:00 UTC
if you find the [dashboard](https://codeamp.checkrhq.net/projects/checkr-dashboard/production/releases) release from May 23 at 13:13 the ui shows that the docker build and tests failed but they [passed](https://circleci.com/gh/checkr/dashboard/5425?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) and the deploy was successful

**Comment by aballman** [comment] 2018-07-24 18:29
Closing as not able to reproduce

**Closed by aballman** 2018-07-24 18:29 UTC
Labels: P/Medium, S/Can't Reproduce, T/Bug
