### ISSUE TITLE
WebSocket message for release completed updates release page with wrong objects

### ISSUE THREAD

**Issue by drshrey** [codeamp/panel#190] opened 2018-07-09 18:40 UTC
**Describe the bug**
When I'm deploying releases from multiple envs for a project at once, the page with Environment A Release objects is updated Environment B Release objects.

**To Reproduce**
1. Go to features page in Environment A in a project and open a new window with Environment B
2. Deploy the feature in both environments
3. Go to the releases page in Environment A
4. You should see it updated with Environment B objects

**Expected behavior**
Environment A should only have environment A objects updated

**Desktop (please complete the following information):**
 - Chrome browser

**Comment by aballman** [comment] 2018-11-29 00:42
This seems related to the issues that were fixed in https://github.com/codeamp/panel/pull/288.

The websocket message updates based off of the path of the URL that was matched on the panel side. If the url does not match the data being displayed (in the case of the environments bug) then this will not update properly. Instead of matching against the url, we should rebuild the params to match off of based on the data provided via component props.

**Comment by aballman** [comment] 2018-12-18 02:11
This also could have been related to the issues that were fixed in https://github.com/codeamp/panel/pull/306. I think #306 and #288 together created this issue. The user would end up with multiple websocker handlers listening for different environments.

Its unclear what the behavior would be in that case but theoretically you could have a deployment from one env update the deployments of another env, or it could go so far as to update the page with the wrong data. I'm not sure how the fetch function would work in that case.

I believe this issue is resolved as a result of these two. The repro steps listed above are not able to reproduce the issue on master. If it comes back up, we can reopen, otherwise I am closing.

**Closed by aballman** 2018-12-18 02:11 UTC
Labels: P/High, T/Bug
